#from pymongo import MongoClient
import pymongo
#------------------------! INSERT ONE !------------------------#
# here i using DOCKER container for (mongo) database !
client=pymongo.MongoClient("0.0.0.0",2717)
# (test1) is the name of database , it's created before
mydb=client["test1"]
# this is a new collection , created now ?
mycol=mydb["customers"]
# now we add a customer to the database from this dictionary .
#mydict = {"name":"jhon","address":"Arafa 66"}
# insert_one for add a single row or (document in mongodb) 
#x=mycol.insert_one(mydict)
#print(x)
#------------------------! ---------- !------------------------#
#------------------------! INSERT MANY !------------------------#
# add many documents here with a defult id ? generated by mongo !
lista = [
  { "name": "Amy", "address": "Apple st 652"},
  { "name": "Hannah", "address": "Mountain 21"},
  { "name": "Michael", "address": "Valley 345"},
  { "name": "Sandy", "address": "Ocean blvd 2"},
  { "name": "Betty", "address": "Green Grass 1"},
  { "name": "Richard", "address": "Sky st 331"},
  { "name": "Susan", "address": "One way 98"},
  { "name": "Vicky", "address": "Yellow Garden 2"},
  { "name": "Ben", "address": "Park Lane 38"},
  { "name": "William", "address": "Central st 954"},
  { "name": "Chuck", "address": "Main Road 989"},
  { "name": "Viola", "address": "Sideway 1633"}
]
# if show added succ... it's ok 
#if mycol.insert_many(lista) : print("added successfully !")
#------------------------! ----------- !------------------------#
#----------------! INSERT MANY WITH SPECIFIED ID!---------------#
# this is anthor way to added many rows but with a specified id ..?
lista_id = [
  { "_id": 1, "name": "John", "address": "Highway 37"},
  { "_id": 2, "name": "Peter", "address": "Lowstreet 27"},
  { "_id": 3, "name": "Amy", "address": "Apple st 652"},
  { "_id": 4, "name": "Hannah", "address": "Mountain 21"},
  { "_id": 5, "name": "Michael", "address": "Valley 345"},
  { "_id": 6, "name": "Sandy", "address": "Ocean blvd 2"},
  { "_id": 7, "name": "Betty", "address": "Green Grass 1"},
  { "_id": 8, "name": "Richard", "address": "Sky st 331"},
  { "_id": 9, "name": "Susan", "address": "One way 98"},
  { "_id": 10, "name": "Vicky", "address": "Yellow Garden 2"},
  { "_id": 11, "name": "Ben", "address": "Park Lane 38"},
  { "_id": 12, "name": "William", "address": "Central st 954"},
  { "_id": 13, "name": "Chuck", "address": "Main Road 989"},
  { "_id": 14, "name": "Viola", "address": "Sideway 1633"}
]
# whene u showing the msg ! check your db , to see this doc 
if mycol.insert_many(lista_id) : print("Added successfully !")
#------------------------! ----------- !------------------------#

